name: CD Matrix WorkFlow

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:
      inputs:
          environment-name:
            description: Select the environment to deploy Micro Service
            required: true
            type: environment
          microservice-image-name:
            description: Select the micro service image name
            required: true
            type: string
jobs:
  image-download-job:
    runs-on: ubuntu-latest
    environment: ${{inputs.environment-name}}
    strategy:
        matrix:
            environment-name: [ '${{ inputs.environment-name }}']
            microservice-image-names: [ '${{ inputs.microservice-image-names }}' ]
    steps:
      - name: xxx
        run: |
            echo "The inputs values are ${{ matrix.environment-name }} ${{ matrix.microservice-image-name }}"
            echo "The secret is ${{ secrets.MY_SECRET }}"
        # with:
        #     environment-name: ${{ matrix.environment-name }}
        #     microservice-image-name: $ {{ matrix.microservice-image-name }}

  image-deploy-job:
    needs: image-download-job
    runs-on: ubuntu-latest
    steps:
      - name: xxx
        run: echo "xxx"
