name: CD Matrix WorkFlow

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:
      inputs:
          environment-name:
            description: Select the environment to deploy Micro Service
            required: true
            type: environment
          microservice-image-name:
            description: Select the micro service image name
            required: true
            type: string
jobs:
  image-download-job:
    runs-on: ubuntu-latest
    environment: ${{github.event.inputs.environment-name}}
    strategy:
        matrix:
            environment-name: [ '${{ github.event.inputs.environment-name }}']
            microservice-image-names: [ '${{ github.event.inputs.microservice-image-names }}' ]
    steps:
      - name: Input variables
        run: |
            echo "Environment input value: ${{ github.event.inputs.environment-name }}"
            echo "Images input value: ${{ github.event.inputs.microservice-image-names }}"
      - name: xxx
        run: |
            echo "The inputs values are ${{ matrix.environment-name }} ${{ matrix.microservice-image-names }}"
            echo "The secret is ${{ secrets.MY_SECRET }}"

  image-deploy-job:
    needs: image-download-job
    runs-on: ubuntu-latest
    steps:
      - name: xxx
        run: echo "xxx"
