name: CD Parallel WorkFlow

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:
      inputs:
          environment-name:
            description: Select the environment to deploy Micro Service
            required: true
            type: environment
          microservice-image-name:
            description: Select the micro service image name
            required: true
            type: string
jobs:
  image-download-parallel-job:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment-name }}
    strategy:
        matrix:
            environment-name: [ "${{ inputs.environment-name }}" ]
            microservice-image-names: ${{ fromJson(inputs.microservice-image-name) }}
    steps:
      - name: xxx
        run: |
            echo "The inputs values are ${{ matrix.environment-name }} ${{ matrix.microservice-image-names }}"
            echo "The secret is ${{ secrets.MY_SECRET }}"
  image-deploy-parallel-job:
    needs: image-download-parallel-job
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment-name }}
    strategy:
        matrix:
            environment-name: [ "${{ inputs.environment-name }}" ]
            microservice-image-names: ${{ fromJson(inputs.microservice-image-name) }}
    steps:
      - name: image-deploy-job-step
        run: |
            echo "The inputs values are ${{ matrix.environment-name }} ${{ matrix.microservice-image-names }}"
            echo "The secret is ${{ secrets.MY_SECRET }}"
