name: CD WorkFlow

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:
      inputs:
          environment-name:
            description: Select the environment to deploy Micro Service
            required: true
            type: environment
            
          microservice-name:
            description: Select the micro service
            type: choice
            options:
            - app-a
            - app-b
            - app-c
            - app-d

          microservice-image-name:
            description: Select the micro service image name
            type: string
jobs:
  image-download-job:
    runs-on: ubuntu-latest
    environment: ${{inputs.environment-name}}
    steps:
      - name: xxx
        run: echo " The inputs values are ${{inputs.environment-name}} ${{inputs.microservice-name}} ${{inputs.microservice-image-name}}"

  image-deploy-job:
    needs: image-download-job
    runs-on: ubuntu-latest
    steps:
      - name: xxx
        run: echo "xxx"
