name: CT WorkFlow

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:
      inputs:
          environment-name:
            description: Select the environment where testing will be performed
            required: true
            type: environment
          testing-job-type:
              description: Select the Testing job type
              required: true
              type: choice
              options:
              - progression
              - regression
              - performance
              - load
              - failover
              - bvt
jobs:
  progression-job:
    if: ${{ inputs.testing-job-type }} == 'progression' 
    runs-on: ubuntu-latest
    steps:
      - name: xxx
        run: echo "xxx"
  regression-job:
    if: ${{ inputs.testing-job-type }} == 'regression'
    runs-on: ubuntu-latest
    steps:
      - name: xxx
        run: echo "xxx"
  performance-job:
    if: ${{ inputs.testing-job-type }} == 'performance'
    runs-on: ubuntu-latest
    steps:
      - name: xxx
        run: echo "xxx"
  load-job:
    if: ${{ inputs.testing-job-type }} == 'load'
    runs-on: ubuntu-latest
    steps:
      - name: xxx
        run: echo "xxx"
  failover-job:
    if: ${{ inputs.testing-job-type }} == 'failover'
    runs-on: ubuntu-latest
    steps:
      - name: xxx
        run: echo "xxx"
  bvt-job:
    if: ${{ inputs.testing-job-type }} == 'bvt'
    runs-on: ubuntu-latest
    steps:
      - name: xxx
        run: echo "xxx"
